[book]
authors = ["kuries"]
language = "en"
multilingual = false
src = "docs"
title = "Matrix Cerberus Documentation"

[output.html]
# The source code URL of the repository
git-repository-url = "https://github.com/MatrixDoctors/matrix-cerberus"
